### ISSUE TITLE
SCRIPT ERROR: @qb-pos/server/server.lua:237: attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by OGPandaYT** [Evantually/qb-pos#2]
Any ideas?

**Comment by Evantually** [comment]
A receipt for the business you are using the pos with either does not have the receipt defined in the config, or it does not exist in your items.lua

**Comment by OGPandaYT** [comment]
Ok so I need to make a receipt item for each business and can't just use the universal receipt item?

**Comment by Evantually** [comment]
That's certainly possible. You can check out line 331 of the default config for how to assign a receipt to a business.
